name: telegram message
on:
  issues:
    types: ["closed"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} closed an issue:
            Issue Name: ${{ github.event.issue.title }}
            See changes: ${{ github.event.issue.html_url }}
